### ISSUE TITLE
MemCopyFloat32 Deprecated?

### ISSUE THREAD

**Issue by koenig-dominik** [vulkan-go/demos#2]
In the file vulkandraw.go:662 there is MemCopyFloat32 used, but in the current vulkan-go api there is only Memcopy defined, which only takes []byte

Also in the file helpers.go:70 there is MemCopyByte used which should be changed to Memcopy

**Comment by xlab** [comment]
@koenig-dominik 
Hi! Thanks, indeed this is deprecated, I decided to stick with 1 method that is just an unsafe version of Go's `copy`.

Sad thing is that I forgot to add the corresponding changes to demos in time ;)
I did that within https://github.com/vulkan-go/demos/commit/4f6208b5e52b69c46d00aa95c149d9f2815c7c28 now.

P.S. `[]float32` -> `[]byte` conversion helpers are now part of [linmath](http://github.com/xlab/linmath) Go package. You can simply copy/paste these snippets or just import that package. Thanks for your report.

**Comment by koenig-dominik** [comment]
Thanks a lot!
