### ISSUE TITLE
Graphics card / os dependencies

### ISSUE THREAD

**Issue by joeblew99** [vulkan-go/demos#3]
I want to try this.

Will I be able to build / compile / run on a macbook ?

What about windows ?

**Comment by xlab** [comment]
Hi @joeblew99 

For **OS X / macOS** you'll need to install the latest GLFW 3.3 from master https://github.com/glfw/glfw
and prepare MoltenVK https://moltengl.com/moltenvk/ SDK beforehand so CMake could find it.

There is a Makefile https://github.com/vulkan-go/demos/blob/master/vulkancube/vulkancube_desktop/Makefile to show how to properly invoke `go install` specifying the path to GLFW.

For **Windows** you don't need to compile MoltenVK and can use GLFW 3.2.1 distro from the site http://www.glfw.org then just specify paths in Makefile or run commands by hand, specifying paths to GLFW distro folders.

Make sure your graphics card and driver are supported:
* https://developer.nvidia.com/vulkan-driver
* http://www.amd.com/en-us/innovations/software-technologies/technologies-gaming/vulkan

In all cases you will run `XXX_desktop` demos.

**Comment by joeblew99** [comment]
Thanks @xlab

Am disappointed they charge so much for the license.  Grumble grumble ....

Will have a play anyway.
Benchmark of OpenGL versus Vulkan Spinning the same triangle will be a useful thing

**Comment by xlab** [comment]
> Benchmark of OpenGL versus Vulkan

Don't expect much from benchmarks at this stage, however I wonder what the difference will be.

> Am disappointed they charge so much for the license. 

You can use it absolutely free, but there will be a watermark. For playing around this is feasible. And MoltenVK is not a real driver like NVIDIA would provide for their GPUs, so it would still be not fair to benchmark using MoltenVK.

**Comment by joeblew99** [comment]
Benchmark. I expected it to not be optomised. The reason i want to ad it is so we can run the benchmarks as we code things and se if changes to the code are impacting perf. Good regression testing best practice. Having a Spinning Triangle in golang / openGl is also a nice benchmark for Us and others to see how it compares too. 

Could you add the Dependencies to the README so others also see this ?

**Comment by xlab** [comment]
> Could you add the Dependencies to the README so others also see this ?

Done
